### ISSUE TITLE
Go常见问题之代码检查

### ISSUE THREAD

**Issue by WGrape** [WGrape/Blog#211]
## 代码检查工具
代码检查工具可以完成代码的静态检查，在go中可以使用[golangci-lint](https://github.com/golangci/golangci-lint)来实现。

### 如何安装

```bash
brew install golangci-lint

brew uninstall golangci-lint

golangci-lint run

golangci-lint run -v
```

或者使用这种方法
```bash
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2
```

## .golangci.yml 配置文件

```yaml
# Linters configurations: https://golangci-lint.run/usage/configuration/#linters-configuration
run:
  # The default concurrency value is the number of available CPU.
  concurrency: 1

# A list of supported linters: https://golangci-lint.run/usage/linters/
linters:
  disable:
    - dogsled # staticcheck .etc
```

### 1、protobuf/proto is deprecated

```
SA1019: "github.com/golang/protobuf/proto" is deprecated: Use the "google.golang.org/protobuf/proto" package instead. (staticcheck)
```

解决方案 ：https://github.com/golang/protobuf/issues/1077

### 2、context loading failed: no go files to analyze
如果出现这个问题，可以使用go build编译下看看是否能成功（大概率是不能成功的），可能原因是依赖项没有下载，所以执行正常下载编译逻辑即可。

https://github.com/golangci/golangci-lint/issues/825
https://github.com/golangci/golangci-lint/issues/825#issuecomment-1229384847

### 3、could not load export data: no export data for
这个错误是因为缺少下载的包，即没有下载对应的依赖包。

```bash
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: inspect: failed to load package : could not load export data: no export data for
```

### 4、WriteFile not declared by package os (typecheck)
一般出现这个问题的原因是Go版本的问题，尝试更新更高版本。

![image](https://user-images.githubusercontent.com/35942268/187828266-a25e8698-dab8-445f-88fa-4241090d43a5.png)
