### ISSUE TITLE
Go常见问题之复杂interface结构的断言

### ISSUE THREAD

**Issue by WGrape** [WGrape/Blog#22]
## 一、问题
在Go语言的实际开发中，通常会遇到```断言```一种```复杂interface结构```的情况。如对YAML等配置文件解析时，需要多次嵌套循环和类型断言才能解析完成。

对于这种复杂结构的断言，可能很难一次性完全写对，经常需要调试多次才能Run。

如何解决这种问题，提高开发效率呢 ？

## 二、复现问题
当前有YAML配置内容如下，如何把这个配置内容解析到Go内存的数据结构中呢

```yaml
strategy:
  factor:
    - gender=0:
        gender=1: 10
        gender=0: 5
    - gender=1:
        gender=0: 10
        gender=1: 5
```

![image](https://user-images.githubusercontent.com/35942268/151503408-8aa87189-6f88-4316-93f6-fb0b6aac3fae.png)

## 三、解决方案
在使用```Goland```调试过程中，调试器会显示每个 interface{} 类型变量真正的数据类型，所以就可以使用这个技巧轻松得到断言时应该使用的类型。

如上图中 item 变量的类型为 ```interface{} | map[interface{}]interface{}``` ，这时在代码中就知道断言应该使用什么类型了。
